# Schema for the configuration files of the Lodgify module.
lodgify.settings:
  type: config_object
  label: 'Lodgify settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'